/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/auth/change-password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Change the current user's password
     * @description Rotate the password for the authenticated user and invalidate outstanding JWTs.
     */
    post: operations["change_password_api_auth_change_password_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/force-logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Invalidate every issued JWT
     * @description Bump the global token version so every previously issued JWT is rejected.
     */
    post: operations["force_logout_api_auth_force_logout_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Authenticate and issue a JWT
     * @description Verify credentials and return a 24-hour JWT in both the body and an HTTP-only cookie.
     */
    post: operations["login_api_auth_login_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Clear the auth cookie
     * @description Drop the ``token`` cookie. JWTs are stateless, so this only affects the browser.
     */
    post: operations["logout_api_auth_logout_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Return the caller's profile
     * @description Return the username embedded in the caller's JWT plus any forced-rotation flag.
     */
    get: operations["me_api_auth_me_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/chat/sessions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List saved chat sessions
     * @description Return every persisted chat session ordered by ``updated_at`` descending.
     */
    get: operations["list_sessions_api_chat_sessions_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/chat/sessions/{session_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Load a chat session
     * @description Return the stored title, timestamps, and full message transcript for ``session_id``.
     */
    get: operations["load_session_api_chat_sessions__session_id__get"];
    put?: never;
    /**
     * Upsert a chat session
     * @description Create or overwrite the persisted transcript for ``session_id``.
     */
    post: operations["save_session_api_chat_sessions__session_id__post"];
    /**
     * Delete a chat session
     * @description Remove the persisted chat session document identified by ``session_id``.
     */
    delete: operations["delete_session_api_chat_sessions__session_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/documents": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List uploaded documents
     * @description Aggregate stored chunks by source filename and return per-document summaries.
     */
    get: operations["list_documents_api_documents_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/documents/status/{filename}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Check embedding-generation status
     * @description Return the lifecycle state of the background embedding job for ``filename``.
     */
    get: operations["get_upload_status_api_documents_status__filename__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/documents/upload": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Upload a PDF/DOCX/TXT document
     * @description Validate, store, and schedule embedding generation for an uploaded document.
     */
    post: operations["upload_document_api_documents_upload_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/documents/{filename}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Delete a document and its chunks
     * @description Remove every stored chunk whose ``source_filename`` matches ``filename``.
     */
    delete: operations["delete_document_api_documents__filename__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Liveness probe
     * @description Return ``{"status": "ok"}`` so load balancers can confirm the process is up.
     */
    get: operations["health_check_api_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/settings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Read stored Couchbase settings
     * @description Return stored settings, including secret fields.
     *
     *     Authenticated callers get the same view they'd see in any password
     *     manager: the secret values are echoed so the UI can pre-fill inputs
     *     that render as ``type=password`` (dot-masked), with an eye toggle
     *     revealing plaintext on demand. The on-disk store stays
     *     Fernet-encrypted regardless.
     */
    get: operations["get_settings_api_settings_get"];
    put?: never;
    /**
     * Save Couchbase settings and reconnect
     * @description Persist new connection settings, reconnect to Couchbase, and re-run index setup.
     *
     *     In Capella mode (and only when a Capella API key is configured), the
     *     DB user and bucket are auto-created via the Management API before the
     *     SDK connect attempt. The Docker scenario relies on
     *     ``couchbase_service._init_docker_cluster`` to bootstrap services /
     *     quotas / admin — that's invoked from inside ``connect()``.
     */
    post: operations["save_settings_api_settings_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/settings/progress": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Current Save & Connect progress stage
     * @description Return the stage of the most recent (or in-flight) Save & Connect.
     *
     *     Polled by the Settings UI on ~0.5s intervals while the form is
     *     submitting so the button label can advance through "applying",
     *     "connecting", "creating_collections", "building_search_index", etc.
     *     The POST /api/settings call itself only resolves at the end of the
     *     multi-step setup, so without this endpoint the user has no
     *     indication of which step is currently running.
     */
    get: operations["settings_progress_api_settings_progress_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/settings/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Check Couchbase connection status
     * @description Return whether the server currently holds a live Couchbase connection.
     *
     *     Falls back to the on-disk settings file if this worker's in-memory
     *     ``cb_initialized`` flag is False. Multi-worker deployments only run
     *     lifespan-init once per process, so a request can land on a worker that
     *     missed the original Save & Connect even though the cluster is fully
     *     set up. In that case we lazily apply the saved settings + reconnect on
     *     the worker, mirroring what lifespan would have done.
     */
    get: operations["settings_status_api_settings_status_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** Body_upload_document_api_documents_upload_post */
    Body_upload_document_api_documents_upload_post: {
      /** File */
      file: string;
    };
    /**
     * ChangePasswordRequest
     * @description Payload for ``POST /api/auth/change-password``.
     */
    ChangePasswordRequest: {
      /**
       * Current Password
       * Format: password
       */
      current_password: string;
      /**
       * New Password
       * Format: password
       */
      new_password: string;
    };
    /**
     * ChatMessage
     * @description One transcript entry exchanged between the user and the assistant.
     */
    ChatMessage: {
      /**
       * Role
       * @enum {string}
       */
      role: "user" | "assistant";
      /** Text */
      text: string;
    };
    /**
     * ChatSessionDetail
     * @description Full chat session document including the message transcript.
     */
    ChatSessionDetail: {
      /** Created At */
      created_at: string;
      /** Messages */
      messages: components["schemas"]["ChatMessage"][];
      /** Session Id */
      session_id: string;
      /** Title */
      title: string;
      /** Updated At */
      updated_at: string;
    };
    /**
     * ChatSessionSummary
     * @description One entry in the chat session list (metadata only, no messages).
     */
    ChatSessionSummary: {
      /** Created At */
      created_at: string;
      /** Session Id */
      session_id: string;
      /** Title */
      title: string;
      /** Updated At */
      updated_at: string;
    };
    /**
     * DocumentSummary
     * @description One entry in the uploaded-document listing.
     */
    DocumentSummary: {
      /** Chunk Count */
      chunk_count: number;
      /** Embedding Method */
      embedding_method?: string | null;
      /** Filename */
      filename: string;
      /** Workflow Name */
      workflow_name?: string | null;
    };
    /**
     * ForceLogoutResponse
     * @description Returned after bumping the global JWT version (invalidates all tokens).
     */
    ForceLogoutResponse: {
      /** Message */
      message: string;
      /**
       * Ok
       * @default true
       */
      ok: boolean;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * JobStatusResponse
     * @description Current embedding-generation state for a previously uploaded filename.
     */
    JobStatusResponse: {
      /** Chunk Count */
      chunk_count?: number | null;
      /** Error */
      error?: string | null;
      /** Method */
      method?: string | null;
      /** Processed Files */
      processed_files?: number | null;
      /** Status */
      status: string;
      /** Total Files */
      total_files?: number | null;
    };
    /**
     * LoginRequest
     * @description Credentials submitted to ``POST /api/auth/login``.
     */
    LoginRequest: {
      /**
       * Password
       * Format: password
       */
      password: string;
      /** Username */
      username: string;
    };
    /**
     * LoginResponse
     * @description Issued JWT plus the flag that drives the password-change flow.
     */
    LoginResponse: {
      /** Must Change Password */
      must_change_password: boolean;
      /** Token */
      token: string;
      /** Username */
      username: string;
    };
    /**
     * MeResponse
     * @description Profile summary for the caller's JWT.
     */
    MeResponse: {
      /** Must Change Password */
      must_change_password: boolean;
      /** Username */
      username: string;
    };
    /**
     * OkMessageResponse
     * @description Acknowledgement with an optional human-readable message.
     * @example {
     *       "ok": true
     *     }
     */
    OkMessageResponse: {
      /** Message */
      message: string;
      /**
       * Ok
       * @default true
       */
      ok: boolean;
    };
    /**
     * OkResponse
     * @description Generic acknowledgement payload used by idempotent mutating endpoints.
     * @example {
     *       "ok": true
     *     }
     */
    OkResponse: {
      /**
       * Ok
       * @default true
       */
      ok: boolean;
    };
    /**
     * SaveSessionRequest
     * @description Payload for persisting a chat session's title and message history.
     */
    SaveSessionRequest: {
      /** Messages */
      messages: components["schemas"]["ChatMessage"][];
      /** Title */
      title: string;
    };
    /**
     * SaveSettingsResponse
     * @description Acknowledgement returned after a successful settings save + reconnect.
     */
    SaveSettingsResponse: {
      /** Message */
      message: string;
      /**
       * Ok
       * @default true
       */
      ok: boolean;
    };
    /**
     * SettingsProgressResponse
     * @description Current stage of the most recent (or in-flight) Save & Connect.
     */
    SettingsProgressResponse: {
      /**
       * Stage
       * @description One of: idle, applying, capella_user, capella_bucket, connecting, creating_bucket, creating_collections, creating_indexes, building_search_index, saving, done, error.
       */
      stage: string;
    };
    /**
     * SettingsRequest
     * @description Cluster + OpenAI settings submitted by the Settings UI.
     */
    SettingsRequest: {
      /**
       * Azure Openai Endpoint
       * @description Azure OpenAI resource URL (https://...).
       */
      azure_openai_endpoint: string;
      /**
       * Capella Api Key Id
       * Format: password
       * @description Capella Management API key ID (only when EMBEDDING_METHOD=capella).
       * @default
       */
      capella_api_key_id: string;
      /**
       * Capella Api Key Token
       * Format: password
       * @description Capella Management API key token.
       * @default
       */
      capella_api_key_token: string;
      /**
       * Capella Workflow Name
       * @description Capella AI Workflow name. Backend looks for an existing workflow with this name on the cluster and reuses it; creates one with this exact name if none exists.
       * @default realtime_rag_vectorization
       */
      capella_workflow_name: string;
      /** Cb Bucket */
      cb_bucket: string;
      /**
       * Cb Collection
       * @description Collection name. UI auto-fills from ``embedding_method`` (documents_local / documents_capella) but the user can override.
       */
      cb_collection: string;
      /**
       * Cb Connection String
       * @description ``couchbases://...`` endpoint.
       */
      cb_connection_string: string;
      /**
       * Cb Password
       * Format: password
       */
      cb_password: string;
      /**
       * Cb Scope
       * @default _default
       */
      cb_scope: string;
      /**
       * Cb Search Index
       * @description Vector search index name. Auto-filled by UI based on mode.
       */
      cb_search_index: string;
      /** Cb Username */
      cb_username: string;
      /**
       * Deepgram Api Key
       * Format: password
       * @description Deepgram primary STT API key (Whisper is the fallback when blank).
       * @default
       */
      deepgram_api_key: string;
      /**
       * Embedding Method
       * @description One of ``capella`` (AI Services workflow) or ``python`` (local).
       * @default capella
       */
      embedding_method: string;
      /**
       * Openai Api Key
       * Format: password
       * @description Azure OpenAI API key.
       */
      openai_api_key: string;
      /**
       * Openai Embedding Model
       * @description Azure OpenAI embedding deployment name.
       */
      openai_embedding_model: string;
      /**
       * Openai Realtime Model
       * @description Azure OpenAI Realtime deployment name.
       */
      openai_realtime_model: string;
      /**
       * Tavily Api Key
       * Format: password
       * @description Tavily key for the web-search fallback.
       * @default
       */
      tavily_api_key: string;
      /**
       * Web Search Enabled
       * @description Enable Tavily web-search fallback when KB has no relevant results.
       * @default false
       */
      web_search_enabled: boolean;
    };
    /**
     * SettingsResponse
     * @description Envelope for :class:`SettingsValues`.
     */
    SettingsResponse: {
      settings: components["schemas"]["SettingsValues"];
    };
    /**
     * SettingsStatusResponse
     * @description Whether the backend currently has a live Couchbase connection.
     */
    SettingsStatusResponse: {
      /** Initialized */
      initialized: boolean;
    };
    /**
     * SettingsValues
     * @description Settings payload returned to the UI. Secret fields come back blank.
     */
    SettingsValues: {
      /** Azure Openai Endpoint */
      azure_openai_endpoint: string;
      /** Capella Api Key Id */
      capella_api_key_id: string;
      /** Capella Api Key Token */
      capella_api_key_token: string;
      /** Capella Workflow Name */
      capella_workflow_name: string;
      /** Cb Bucket */
      cb_bucket: string;
      /** Cb Collection */
      cb_collection: string;
      /** Cb Connection String */
      cb_connection_string: string;
      /** Cb Password */
      cb_password: string;
      /** Cb Scope */
      cb_scope: string;
      /** Cb Search Index */
      cb_search_index: string;
      /** Cb Username */
      cb_username: string;
      /** Deepgram Api Key */
      deepgram_api_key: string;
      /** Embedding Method */
      embedding_method: string;
      /** Openai Api Key */
      openai_api_key: string;
      /** Openai Embedding Model */
      openai_embedding_model: string;
      /** Openai Realtime Model */
      openai_realtime_model: string;
      /** Tavily Api Key */
      tavily_api_key: string;
      /** Web Search Enabled */
      web_search_enabled: boolean;
    };
    /**
     * UploadResponse
     * @description Returned immediately after a PDF upload is accepted for processing.
     */
    UploadResponse: {
      /** Chunk Count */
      chunk_count: number;
      /** Filename */
      filename: string;
      /**
       * Status
       * @description Lifecycle state: vectorizing, completed, failed, unknown.
       * @default vectorizing
       */
      status: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  change_password_api_auth_change_password_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChangePasswordRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OkMessageResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  force_logout_api_auth_force_logout_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ForceLogoutResponse"];
        };
      };
    };
  };
  login_api_auth_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LoginResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  logout_api_auth_logout_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OkMessageResponse"];
        };
      };
    };
  };
  me_api_auth_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MeResponse"];
        };
      };
    };
  };
  list_sessions_api_chat_sessions_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChatSessionSummary"][];
        };
      };
    };
  };
  load_session_api_chat_sessions__session_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChatSessionDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  save_session_api_chat_sessions__session_id__post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SaveSessionRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OkResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_session_api_chat_sessions__session_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OkResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_documents_api_documents_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DocumentSummary"][];
        };
      };
    };
  };
  get_upload_status_api_documents_status__filename__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        filename: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JobStatusResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  upload_document_api_documents_upload_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_upload_document_api_documents_upload_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UploadResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_document_api_documents__filename__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        filename: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OkResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  health_check_api_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  get_settings_api_settings_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SettingsResponse"];
        };
      };
    };
  };
  save_settings_api_settings_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SettingsRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SaveSettingsResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  settings_progress_api_settings_progress_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SettingsProgressResponse"];
        };
      };
    };
  };
  settings_status_api_settings_status_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SettingsStatusResponse"];
        };
      };
    };
  };
}
